sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t loessplateau/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true loessplateau/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-example"
#   env: "Dockerexample-env"
#   bucket_name: "elasticbeanstalk-us-east-1-656998550690"
#   bucket_path: "docker-example"
#   on: 
#     branch: master
  # access_key_id: "$AWS_ACCESS_KEY"
  # secret_access_key: "$AWS_SECRET_KEY"
